title: Elizabeth Perez Silva
logo: /assets:img/headshot.png
#description: Hi! I'm Elizabeth Perez, a budding Data Analyst with a background in Accounting and Business Administration. I'm passionate about leveraging data to drive decision-making and uncover insights. Here, you'll find my projects showcasing my skills in Python, SQL, Excel, Tableau, R, and VBA.
show_downloads: false
theme: jekyll-theme-minimal
